### ISSUE TITLE
Usage of precompiled headers

### ISSUE THREAD

**Issue by mirkow** [onqtam/ucm#1]
I did not really get how to use the precompiled headers with ucm.

There is in the ucm_add_target() the PCH parameter. This probably should activate the usage of the generated pch.
But when I compile this target with -H as compile flag there is no precompiled header used. Only if I specified a header file with the PCH_FILE parameter.
Is this the expected behavior?

Though, this is not a big problem for me, because I want to specify the precompiled header myself.
I want to use the same pch for every target and it should only be compiled once. Is this possible with ucm?

**Comment by onqtam** [comment]
I am not sure you need to pass -H to anything when using the pch generation of cotire.
I haven't tested using only the PCH flag without PCH_FILE but it should just be forwarded to cotire...
Anyway I wouldn't use a pch not maintained by me and I always use PCH_FILE.
I also dont think that you can get cotire to generate a pch and to make a unity at the same time - not sure about this - but you can make a unity target and give it a specific pch to use - that works.

About sharing the same pch between multiple targets - that'a a feature that I too want very much and am blabbering about it here: https://github.com/sakra/cotire/issues/72

**Comment by mirkow** [comment]
OK, thanks.

regarding the global pch, I do it like this now:

in the main target I do:

```
get_target_property(_precompiledHeader "${LIB_NAME}_ORIGINAL" COTIRE_CXX_PREFIX_HEADER)
SET_PROPERTY(GLOBAL PROPERTY PACKAGE_PCH "${_precompiledHeader}")
```

after setting up each of the other targets with ucm_add_target I do:

```
GET_PROPERTY(PCH_FILE GLOBAL PROPERTY PACKAGE_PCH)
if(PCH_FILE)
        message("Using package pch: ${PCH_FILE}")
        add_definitions(" -include ${PCH_FILE} -Winvalid-pch")
endif()
```

Seems to work so far, but the speed up ist not good yet

**Comment by onqtam** [comment]
Well I am still not sure why you need to add `-include <pch> -Winvalid-pch` since cotire does that itself. Can you post a minimal example where that is absolutely required?
