### ISSUE TITLE
As of 37303d8, ucm_add_linker_flags is broken

### ISSUE THREAD

**Issue by ruifig** [onqtam/ucm#11]
Example of something we have for Visual Studio 2015:
`
ucm_add_linker_flags(EXE /DEBUG:Fastlink CONFIG Release)
`

This worked fine before. It adds that option to the "Configuration Properties->Linker->Generate Debug Info" project property.
As of 37303d8, it doesn't do anything.

**Comment by ruifig** [comment]
Just figured out that if I use uppercase, it works. E.g:
`
ucm_add_linker_flags(EXE /DEBUG:Fastlink CONFIG RELEASE)
`

My Cmake skills are rubbish, so I couldn't figure out how commit 37303d8 broke that behaviour.

**Comment by ruifig** [comment]
As a side note, I was following the provided help, which gives the following example:
`
ucm_add_linker_flags(/NXCOMPAT) 
ucm_add_linker_flags(EXE /DYNAMICBASE CONFIG Release)
ucm_add_flags(EXE /DYNAMICBASE CONFIG Debug Release)
`

**Comment by onqtam** [comment]
should be fixed now - thanks for the catch!
